# Generated by Django 5.2.3 on 2025-06-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_cantidad_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
    ]
